spring:
  application:
    name: AppointmentWorkerApplication

  datasource:
    url: jdbc:h2:file:../data/appointment-db;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      pool-name: AppointmentWorkerHikariPool
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 900000
      validation-timeout: 2000
      leak-detection-threshold: 30000

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
    consumer:
      group-id: appointment-group
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer

appointment:
  kafka:
    topic: appointment-events-topic
    dlt:
      suffix: -dlt
      deserialization-suffix: -deserialization-dlt
    retry:
      backoff-interval-ms: 1000
      max-attempts: 2

logging:
  file:
    name: logs/appointment-worker.log
  structured:
    format:
      file: ecs
