spring:
  application:
    name: AppointmentApplication

  datasource:
    url: jdbc:h2:mem:appointment-db
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      pool-name: AppointmentHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 900000
      validation-timeout: 2000
      leak-detection-threshold: 30000

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  paths-to-match: /api/**
  packages-to-scan: com.desafio.agendamento.adapters.in.controller

response:
  error-messages:
    invalid-cpf: CPF must contain exactly 11 digits.
    appointment-with-invalid-date: It's not possible to create an appointment with a date in the past.
