spring:
  application:
    name: AppointmentApplication

  datasource:
    url: jdbc:h2:mem:appointment-db
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
    consumer:
      group-id: appointment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  paths-to-match: /api/**
  packages-to-scan: com.appointment.adapters.in.controller

response:
  error-messages:
    invalid-cpf: It's not possible create a appointment with invalid CPF. Try again
    appointment-with-invalid-date: It's not possible create a appointment with invalid date. Try again